# In-Class Programming Activity, Day 3

Your work goes here ...



## Test statements

```{r}
scoreActivity::score253(3)
```


Task1
```{r}
data(College,package = "ISLR")
```

Task2
```{r}
College$Yield<-College$Enroll/College$Accept
```



```{r}
all_indices<-c(1:nrow(College))
```

```{r}
train_indices<-sample(all_indices,200)
```


```{r}
test_indices<-setdiff(all_indices,train_indices)
```


```{r}
Train_data<-College[train_indices,]
```

```{r}
Test_data<-College[test_indices,]
```

Task 4
```{r}
Yield_mod1 <- lm(Yield ~ Top10perc + Outstate + Expend,
                 data=Train_data)

```


Task 5

```{r}
Y_train<-Train_data$Yield
```

```{r}
fhat_train<-predict(Yield_mod1,newdata=Train_data)
```

```{r}
 MSE_train=mean((fhat_train-Y_train)^2)
```


Task 5

```{r}
Yield_mod2 <- lm(Yield ~ Top10perc + Outstate + Expend,
                 data=Test_data)

```


Task 5

```{r}
Y_test<-Test_data$Yield
```

```{r}
fhat_test<-predict(Yield_mod2,newdata=Test_data)
```

```{r}
 MSE_test=mean((fhat_test-Y_test)^2)
```

```{r}
MSE_test/MSE_train

```

