# In-Class Programming Activity, Day 5

Your work goes here ...



## Test statements

```{r}
scoreActivity::score253(5)
```
task1
```{r}
nbins=10
```


task 2
```{r}
require(utils)
data(Galton, package = "mosaicData")
mini=min(Galton$height)
maxim=max(Galton$height)
evenly_spaced=seq(mini,maxim,(maxim-mini)/nbins)


```

task3


```{r}
bin_counts=table( cut(Galton$height, b = nbins))

```


task4
```{r}
hist_basics=data.frame(xL=evenly_spaced[1:nbins],xR=evenly_spaced[2:(nbins+1)], count=as.numeric(bin_counts))
```

task5
```{r}
make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}
```

```{r}
My_bars=one_to_five(hist_basics)
```

task6

```{r}
plot(My_bars, type="n")
lines(My_bars)
polygon(My_bars) 

```















