# In-Class Programming Activity, Day 6

Your work goes here ...



## Test statements

```{r}
scoreActivity::score253(6)
```

task1

```{r}

make_one_bar <- function(point) {
  xLeft <- point$xL
  xRight <- point$xR
  height <- point$count
  res <- data.frame(
              x = c(xLeft,  xLeft,  xRight, xRight, NA),
              y = c(    0, height,  height,      0, NA)
  )
  res
}
# ================
one_to_five <- function(hist_data) {
  bars <- NULL
  for (k in 1:nrow(hist_data)) {
    new_bar <- make_one_bar(hist_data[k, ])
    bars <- rbind(bars, new_bar)
  }
  bars
}
```


```{r}
myHistogram=function(v,fill=tomato,nbins){
  evenly_spaced=seq(min(v),max(v),(max(v)-min(v))/nbins)
  bin_counts=table(cut(v, b = nbins))
  hist_basics=data.frame(xL=evenly_spaced[1:nbins],xR=evenly_spaced[2:(nbins+1)], count=as.numeric(bin_counts))
  My_bars=one_to_five(hist_basics)
  plot(My_bars, type="n")
lines(My_bars)
polygon(My_bars,col=fill) 
x <- seq(min(v), max(v), length=100)
lines(x, 3000*dnorm(x,mean=mean(v),sd=sd(v)),col="red")
return(bin_counts)
}
```

```{r}
data(Galton,package='mosaicData')
height=Galton$height
```

```{r}
myHistogram(height,fill="blue",10)
```

