# In-Class Programming Activity, Day 12

Your work goes here ...



## Test statements

```{r}
scoreActivity::score253(12)
```

```{r}
n_cases=100
red_mean=c(1,0)
green_mean=c(0,-1)
blue_mean=c(-1,1)
covar_red=rbind(c(3,-1.7),c(-1.7,1))
covar_blue=rbind(c(2,1.5),c(1.5,3))
One=cbind(rnorm(100,0,1),rnorm(100,0,1))
Two=cbind(rnorm(100,0,1),rnorm(100,0,1))
Three=cbind(rnorm(100,0,1),rnorm(100,0,1))
```

```{r}
Red=One%*%col(covar_red)
Green=Two%*%col(covar_red)
Blue=Three%*%col(covar_blue)
```

```{r}
Red[1]=Red[1]+red_mean[1]
Blue[1]=Blue[1]+blue_mean[1]
Blue[2]=Blue[2]+blue_mean[2]
Green[1]=Green[1]+Green[1]
Green[2]=Green[2]+Green[2]
```

```{r}
Red=data.frame(x=Red[,1],y=Red[,2],class="red",stringsAsFactors = FALSE)

Blue=data.frame(x=Blue[,1],y=Blue[,2],class="blue",stringsAsFactors = FALSE)

Green=data.frame(x=Green[,1],y=Green[,2],class="green",stringsAsFactors = FALSE)

Same_sigma <- rbind(Red, Green)
Different_sigma <- rbind(Red, Blue)
```


```{r}
library(MASS)
mod_LDA_one <- lda(class ~ x + y, data = Same_sigma)
test_LDA_one <- predict(mod_LDA_one, newdata = Same_sigma)
table(Same_sigma$class, test_LDA_one$class)


```

```{r}
mod_LDA_one <- lda(class ~ x + y, data = Different_sigma)
test_LDA_one <- predict(mod_LDA_one, newdata = Different_sigma)
table(Same_sigma$class, test_LDA_one$class)
```

