# Topic 7 Exercises: Nonlinear regression

11.
```{r}
n <- 100
x1 <- rnorm(n, 1, 2)
x2 <- rgamma(n, 1)
err <- rnorm(n, 0, 1)
y <- x1 + 2*x2 + err
```

```{r}
beta1 <- 3
```

```{r}
a = y - beta1 * x1
beta2 = lm(a ~ x2)$coef[2]
```

```{r}
a = y - beta2 * x2
beta1 = lm(a ~ x1)$coef[2]
```





```{r}
a <- NULL
beta0 <- NULL
beta2 <- NULL
beta1 <- 3
        
for (i in 1:1000){
        
        a <- y - beta1[i] * x1
        beta2[i] <- lm(a ~ x2)$coef[2]
        a <- y - beta2[i] * x2
        beta0[i] <- lm(a ~ x1)$coef[1]
        beta1[i+1] <- lm(a ~ x1)$coef[2]
}
betas <- data.frame(beta0, beta1[2:1001], beta2)
colnames(betas) <- c("beta0", "beta1", "beta2")
head(betas,10)
```


```{r}
lmfit.y <- lm(y ~ x1 + x2)
coef(lmfit.y)
```

3.

 −2−1:y=1+x;
 
1-2: y=1+x−2(x−1)2y=1+x−2(x−1)2.

```{r}
x = -2:2
y = 1 + x + -2 * (x-1)^2 * I(x>1)
plot(x, y,type="l")
```








4.
```{r}
x = -2:2
y = c(1 + 0 + 0, # x = -2
      1 + 0 + 0, # x = -1
      1 + 1 + 0, # x = 0
      1 + (1-0) + 0, # x = 1
      1 + (1-1) + 0 # x =2
      )
plot(x,y,type="l")
```


5.
(a) g2
(b)g1
(c)same


